// Store downloads, counted exactly rather than as the "500+" tag a listing
// shows: Google Play's daily install reports and Apple's daily sales
// reports, pulled into Firestore once a day (and on demand from the
// console), one document per day per platform.
//
//   Google Play   The Play Console exports installs to a Cloud Storage
//                 bucket (Download reports → "Copy Cloud Storage URI",
//                 gs://pubsite_prod_…). Once the function's service account
//                 is invited in Users and permissions with "View app
//                 information and download bulk reports", this reads
//                 stats/installs/installs_<package>_<YYYYMM>_overview.csv
//                 (and _country.csv) straight from that bucket. The files
//                 are UTF-16LE CSV with a BOM, one row per day.
//   App Store     App Store Connect's Sales and Trends API (an API key with
//                 the Sales role + the vendor number): one gzip TSV per
//                 day, rows per product type / country. Downloads = units
//                 of the first-time product types (1, 1F, 1T, 1E…);
//                 re-downloads (3*) and updates (7*) are kept apart. A day
//                 with no sales comes back 404 and is stored as zero.
//
//   store_stats/android                  summary (lastSyncAt, error, totals)
//   store_stats/android/days/{YYYY-MM-DD} installs, uninstalls, activeDevices…
//   store_stats/ios                      summary
//   store_stats/ios/days/{YYYY-MM-DD}    downloads, redownloads, updates, iap
//   admin_config/stores                  bucket, package, vendor, key ids
//   admin_config/stores_private          the App Store Connect .p8 key
const admin = require("firebase-admin");
const { logger } = require("firebase-functions");
const crypto = require("node:crypto");
const zlib = require("node:zlib");

const CONFIG_DOC = "admin_config/stores";
const PRIVATE_DOC = "admin_config/stores_private";
const STATS = "store_stats";
const DEFAULT_PACKAGE = "com.KHEasyDev.easy_plate";
const DEFAULT_APPLE_APP_ID = "6809243199";
const ASC_HOST = "https://api.appstoreconnect.apple.com";
const DAY_MS = 24 * 3600 * 1000;
// Apple keeps daily reports for a year; a longer backfill has nothing to find.
const MAX_BACKFILL_DAYS = 365;
// A recent report can still be regenerated by Apple; the daily job re-reads
// the last few days so a late correction lands.
const RECHECK_DAYS = 4;
const IOS_CONCURRENCY = 4;

// ---------------------------------------------------------------------------
// Pure helpers.
// ---------------------------------------------------------------------------

function dayKey(date) {
  return date.toISOString().slice(0, 10);
}

function isDayKey(value) {
  return typeof value === "string" && /^\d{4}-\d{2}-\d{2}$/.test(value) && !Number.isNaN(Date.parse(`${value}T00:00:00Z`));
}

// Each calendar day from `from` to `to` inclusive, as YYYY-MM-DD.
function daysBetween(from, to) {
  const out = [];
  const end = Date.parse(`${to}T00:00:00Z`);
  for (let t = Date.parse(`${from}T00:00:00Z`); t <= end; t += DAY_MS) out.push(dayKey(new Date(t)));
  return out;
}

// A Play export is UTF-16LE with a byte-order mark; a hand-made one may be
// plain UTF-8. Either way the text comes back without the mark.
function decodeReport(buffer) {
  const bytes = Buffer.isBuffer(buffer) ? buffer : Buffer.from(buffer);
  let text;
  if (bytes.length >= 2 && bytes[0] === 0xff && bytes[1] === 0xfe) text = bytes.subarray(2).toString("utf16le");
  else if (bytes.length >= 2 && bytes[0] === 0xfe && bytes[1] === 0xff) text = Buffer.from(bytes.subarray(2)).swap16().toString("utf16le");
  else text = bytes.toString("utf8");
  return text.replace(/^﻿/, "");
}

// Minimal CSV: commas, double quotes, CRLF. Returns rows as arrays.
function parseCsv(text) {
  const rows = [];
  let row = [];
  let cell = "";
  let quoted = false;
  for (let i = 0; i < text.length; i++) {
    const ch = text[i];
    if (quoted) {
      if (ch === '"') {
        if (text[i + 1] === '"') { cell += '"'; i++; } else quoted = false;
      } else cell += ch;
      continue;
    }
    if (ch === '"') quoted = true;
    else if (ch === ",") { row.push(cell); cell = ""; }
    else if (ch === "\n" || ch === "\r") {
      if (ch === "\r" && text[i + 1] === "\n") i++;
      row.push(cell);
      if (row.some((c) => c !== "")) rows.push(row);
      row = [];
      cell = "";
    } else cell += ch;
  }
  row.push(cell);
  if (row.some((c) => c !== "")) rows.push(row);
  return rows;
}

function parseTsv(text) {
  return text.split(/\r?\n/).filter((line) => line.trim() !== "").map((line) => line.split("\t"));
}

const norm = (s) => String(s || "").trim().toLowerCase().replace(/[^a-z0-9]+/g, " ").trim();

// Rows as objects keyed by the normalised header name.
function objects(rows) {
  if (!rows.length) return [];
  const header = rows[0].map(norm);
  return rows.slice(1).map((r) => Object.fromEntries(header.map((k, i) => [k, r[i] === undefined ? "" : String(r[i]).trim()])));
}

const int = (v) => {
  const n = parseInt(String(v || "").replace(/[^-\d]/g, ""), 10);
  return Number.isFinite(n) ? n : 0;
};

// The Play overview export: one row per day. Column names have changed
// over the years, so each figure is looked up by the names it has had.
const PLAY_COLUMNS = {
  installs: ["daily user installs", "user installs"],
  uninstalls: ["daily user uninstalls", "user uninstalls"],
  deviceInstalls: ["daily device installs", "device installs"],
  deviceUninstalls: ["daily device uninstalls", "device uninstalls"],
  upgrades: ["daily device upgrades", "device upgrades"],
  totalUserInstalls: ["total user installs"],
  activeDevices: ["active device installs"],
  installEvents: ["install events"],
  updateEvents: ["update events"],
  uninstallEvents: ["uninstall events"],
};

function pick(row, names) {
  for (const name of names) if (row[name] !== undefined && row[name] !== "") return int(row[name]);
  return 0;
}

// Overview CSV → { "YYYY-MM-DD": { installs, uninstalls, … } } for `pkg`
// (any package when `pkg` is empty).
function parsePlayOverview(text, pkg = "") {
  const days = {};
  for (const row of objects(parseCsv(text))) {
    const date = row.date;
    if (!isDayKey(date)) continue;
    if (pkg && row["package name"] && row["package name"] !== pkg) continue;
    const entry = {};
    for (const [field, names] of Object.entries(PLAY_COLUMNS)) entry[field] = pick(row, names);
    days[date] = entry;
  }
  return days;
}

// Country CSV → { "YYYY-MM-DD": { IL: userInstalls, … } }.
function parsePlayCountries(text, pkg = "") {
  const days = {};
  for (const row of objects(parseCsv(text))) {
    const date = row.date;
    const country = String(row.country || "").toUpperCase();
    if (!isDayKey(date) || !country) continue;
    if (pkg && row["package name"] && row["package name"] !== pkg) continue;
    const n = pick(row, PLAY_COLUMNS.installs);
    if (!n) continue;
    days[date] = days[date] || {};
    days[date][country] = (days[date][country] || 0) + n;
  }
  return days;
}

// Apple product type identifiers. First downloads start with 1 (1, 1F
// universal, 1T iPad, 1E/1EP/1EU custom apps) or F1 on the Mac; 3* are
// re-downloads, 7* updates, IA*/FI* in-app purchases.
function classifyProductType(type) {
  const t = String(type || "").trim().toUpperCase();
  if (/^F?1/.test(t)) return "downloads";
  if (/^F?3/.test(t)) return "redownloads";
  if (/^F?7/.test(t)) return "updates";
  if (/^(IA|FI)/.test(t)) return "iap";
  return null;
}

// One day's sales TSV → { downloads, redownloads, updates, iap, countries,
// devices }. Rows of other apps on the same vendor are skipped when
// `appId` is set; an in-app purchase belongs to the app through its
// parent SKU.
function parseAppleSales(text, appId = "") {
  const out = { downloads: 0, redownloads: 0, updates: 0, iap: 0, countries: {}, devices: {} };
  const rows = objects(parseTsv(text));
  const skus = new Set();
  const want = String(appId || "").trim();
  for (const row of rows) {
    if (want && row["apple identifier"] === want && row.sku) skus.add(row.sku);
  }
  for (const row of rows) {
    const kind = classifyProductType(row["product type identifier"]);
    if (!kind) continue;
    const units = int(row.units);
    if (want) {
      const own = row["apple identifier"] === want;
      const child = kind === "iap" && skus.has(row["parent identifier"]);
      if (!own && !child) continue;
    }
    out[kind] += units;
    if (kind === "downloads") {
      const country = String(row["country code"] || "").toUpperCase();
      if (country) out.countries[country] = (out.countries[country] || 0) + units;
      const device = String(row.device || "").trim();
      if (device) out.devices[device] = (out.devices[device] || 0) + units;
    }
  }
  return out;
}

function normalizePem(raw) {
  let key = String(raw || "").trim();
  if (!key) return "";
  if (key.includes("\\n") && !key.includes("\n")) key = key.replace(/\\n/g, "\n");
  return key.trim();
}

function isPem(key) {
  return /-----BEGIN [A-Z ]*PRIVATE KEY-----/.test(normalizePem(key));
}

const b64url = (data) => Buffer.from(data).toString("base64").replace(/=+$/, "").replace(/\+/g, "-").replace(/\//g, "_");

// The 20-minute ES256 token App Store Connect takes.
function appleJwt({ issuerId, keyId, privateKey, now = Date.now() }) {
  const iat = Math.floor(now / 1000);
  const header = b64url(JSON.stringify({ alg: "ES256", kid: keyId, typ: "JWT" }));
  const payload = b64url(JSON.stringify({ iss: issuerId, iat, exp: iat + 1200, aud: "appstoreconnect-v1" }));
  const signature = crypto.sign("sha256", Buffer.from(`${header}.${payload}`), { key: crypto.createPrivateKey(normalizePem(privateKey)), dsaEncoding: "ieee-p1363" });
  return `${header}.${payload}.${b64url(signature)}`;
}

// What the console shows and stores; the private key never travels back.
function cleanConfig(raw = {}) {
  const s = (v, max = 200) => String(v === undefined || v === null ? "" : v).trim().slice(0, max);
  const out = {
    playBucket: s(raw.playBucket).replace(/^gs:\/\//, "").replace(/\/.*$/, ""),
    playPackage: s(raw.playPackage) || DEFAULT_PACKAGE,
    appleVendor: s(raw.appleVendor, 40).replace(/\D/g, ""),
    appleIssuerId: s(raw.appleIssuerId, 80),
    appleKeyId: s(raw.appleKeyId, 40),
    appleAppId: s(raw.appleAppId, 40).replace(/\D/g, "") || DEFAULT_APPLE_APP_ID,
    iosSince: isDayKey(s(raw.iosSince, 10)) ? s(raw.iosSince, 10) : "",
  };
  return out;
}

function androidConfigured(config) {
  return !!(config.playBucket && config.playPackage);
}

function iosConfigured(config, keyPresent) {
  return !!(config.appleVendor && config.appleIssuerId && config.appleKeyId && keyPresent);
}

// Cumulative figures from the day documents, platform by platform.
function totals(days) {
  const out = { android: { installs: 0, uninstalls: 0 }, ios: { downloads: 0, redownloads: 0, updates: 0, iap: 0 } };
  for (const d of days.android || []) {
    out.android.installs += d.installs || 0;
    out.android.uninstalls += d.uninstalls || 0;
  }
  for (const d of days.ios || []) {
    out.ios.downloads += d.downloads || 0;
    out.ios.redownloads += d.redownloads || 0;
    out.ios.updates += d.updates || 0;
    out.ios.iap += d.iap || 0;
  }
  return out;
}

// ---------------------------------------------------------------------------
// Firestore.
// ---------------------------------------------------------------------------

async function loadConfig(db) {
  const [doc, priv] = await Promise.all([db.doc(CONFIG_DOC).get(), db.doc(PRIVATE_DOC).get()]);
  const config = cleanConfig(doc.exists ? doc.data() : {});
  const privateKey = priv.exists ? normalizePem(priv.get("applePrivateKey")) : "";
  return { config, privateKey, keyPresent: isPem(privateKey) };
}

async function saveConfig(db, patch) {
  const current = await loadConfig(db);
  const next = cleanConfig({ ...current.config, ...patch });
  await db.doc(CONFIG_DOC).set({ ...next, updatedAt: admin.firestore.FieldValue.serverTimestamp() }, { merge: true });
  if (patch.applePrivateKey !== undefined) {
    const key = normalizePem(patch.applePrivateKey);
    if (key && !isPem(key)) throw Object.assign(new Error("The private key must be the .p8 file's contents (BEGIN PRIVATE KEY)"), { status: 400, code: "invalid" });
    if (key) await db.doc(PRIVATE_DOC).set({ applePrivateKey: key, updatedAt: admin.firestore.FieldValue.serverTimestamp() });
    else await db.doc(PRIVATE_DOC).delete();
  }
  return loadConfig(db);
}

async function writeDays(db, platform, days) {
  const entries = Object.entries(days);
  for (let i = 0; i < entries.length; i += 400) {
    const batch = db.batch();
    for (const [date, data] of entries.slice(i, i + 400)) batch.set(db.doc(`${STATS}/${platform}/days/${date}`), { ...data, date }, { merge: false });
    await batch.commit();
  }
  return entries.length;
}

async function markSync(db, platform, patch) {
  await db.doc(`${STATS}/${platform}`).set({ ...patch, lastSyncAt: admin.firestore.FieldValue.serverTimestamp() }, { merge: true });
}

// The service account the function runs as: the email to invite in the
// Play Console. Cloud Run answers on the metadata server; elsewhere the
// project's default compute account is the usual answer.
async function serviceAccountEmail(fetchImpl = fetch) {
  try {
    const res = await fetchImpl("http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/email", { headers: { "Metadata-Flavor": "Google" }, signal: AbortSignal.timeout(1500) });
    if (res.ok) return (await res.text()).trim();
  } catch (_) {}
  const project = process.env.GCLOUD_PROJECT || "";
  return project ? `(the default compute service account of ${project})` : "";
}

// ---------------------------------------------------------------------------
// Google Play.
// ---------------------------------------------------------------------------

async function syncAndroid({ db, config, storage = admin.storage() }) {
  if (!androidConfigured(config)) throw Object.assign(new Error("Play bucket not configured"), { status: 400, code: "not_configured" });
  const bucket = storage.bucket(config.playBucket);
  const pkg = config.playPackage;
  let files;
  try {
    [files] = await bucket.getFiles({ prefix: "stats/installs/" });
  } catch (err) {
    const reason = err.code === 403 ? `no access to gs://${config.playBucket} — invite the function's service account in Play Console → Users and permissions` : err.message;
    await markSync(db, "android", { error: reason });
    throw Object.assign(new Error(reason), { status: 502, code: "play_access" });
  }
  const overview = files.filter((f) => f.name.endsWith("_overview.csv") && f.name.includes(`installs_${pkg}_`));
  const country = files.filter((f) => f.name.endsWith("_country.csv") && f.name.includes(`installs_${pkg}_`));
  const days = {};
  for (const file of overview) {
    const [buf] = await file.download();
    Object.assign(days, parsePlayOverview(decodeReport(buf), pkg));
  }
  for (const file of country) {
    const [buf] = await file.download();
    for (const [date, map] of Object.entries(parsePlayCountries(decodeReport(buf), pkg))) {
      if (days[date]) days[date].countries = map;
    }
  }
  const written = await writeDays(db, "android", days);
  const dates = Object.keys(days).sort();
  const last = dates.length ? days[dates[dates.length - 1]] : null;
  await markSync(db, "android", {
    error: null,
    files: overview.length,
    days: dates.length,
    firstDay: dates[0] || null,
    lastDay: dates[dates.length - 1] || null,
    totalUserInstalls: last ? last.totalUserInstalls : 0,
    activeDevices: last ? last.activeDevices : 0,
  });
  logger.info("play stats synced", { files: overview.length, days: written });
  return { platform: "android", files: overview.length, days: written, lastDay: dates[dates.length - 1] || null };
}

// ---------------------------------------------------------------------------
// App Store.
// ---------------------------------------------------------------------------

async function fetchAppleDay({ config, token, date, fetchImpl = fetch }) {
  const params = new URLSearchParams({
    "filter[frequency]": "DAILY",
    "filter[reportDate]": date,
    "filter[reportSubType]": "SUMMARY",
    "filter[reportType]": "SALES",
    "filter[vendorNumber]": config.appleVendor,
  });
  const res = await fetchImpl(`${ASC_HOST}/v1/salesReports?${params}`, { headers: { Authorization: `Bearer ${token}`, Accept: "application/a-gzip" } });
  if (res.status === 404) return { ...parseAppleSales("", config.appleAppId), missing: true };
  if (!res.ok) {
    let detail = "";
    try {
      const json = await res.json();
      detail = json && json.errors && json.errors[0] ? `${json.errors[0].title || ""} ${json.errors[0].detail || ""}`.trim() : "";
    } catch (_) {}
    const hint = res.status === 401 ? "the key, key id or issuer id is wrong" : res.status === 403 ? "the key has no Sales and Reports access, or the vendor number is not yours" : "";
    throw Object.assign(new Error(`App Store Connect ${res.status}${detail ? `: ${detail}` : ""}${hint ? ` (${hint})` : ""}`), { status: 502, code: "apple_access" });
  }
  const bytes = Buffer.from(await res.arrayBuffer());
  let text;
  try {
    text = zlib.gunzipSync(bytes).toString("utf8");
  } catch (_) {
    text = bytes.toString("utf8");
  }
  return parseAppleSales(text, config.appleAppId);
}

// Pulls the days not yet stored (plus the last few, which Apple may still
// correct), or everything since `config.iosSince` on a backfill.
async function syncIos({ db, config, privateKey, fetchImpl = fetch, backfill = false, now = Date.now() }) {
  if (!iosConfigured(config, isPem(privateKey))) throw Object.assign(new Error("App Store Connect not configured"), { status: 400, code: "not_configured" });
  // Yesterday is the newest report Apple has.
  const yesterday = dayKey(new Date(now - DAY_MS));
  const earliest = dayKey(new Date(now - MAX_BACKFILL_DAYS * DAY_MS));
  const stored = await db.collection(`${STATS}/ios/days`).select("date").get();
  const have = new Set(stored.docs.map((d) => d.id));
  const from = config.iosSince && config.iosSince > earliest ? config.iosSince : earliest;
  // Days never stored, plus the newest few whatever is stored.
  const recheckFrom = dayKey(new Date(now - (RECHECK_DAYS + 1) * DAY_MS));
  const wanted = daysBetween(from, yesterday).filter((d) => backfill || !have.has(d) || d >= recheckFrom);
  let token = appleJwt({ issuerId: config.appleIssuerId, keyId: config.appleKeyId, privateKey, now });
  let minted = now;
  const days = {};
  let index = 0;
  const worker = async () => {
    while (index < wanted.length) {
      const date = wanted[index++];
      if (Date.now() - minted > 15 * 60 * 1000) {
        token = appleJwt({ issuerId: config.appleIssuerId, keyId: config.appleKeyId, privateKey });
        minted = Date.now();
      }
      days[date] = await fetchAppleDay({ config, token, date, fetchImpl });
    }
  };
  try {
    await Promise.all(Array.from({ length: Math.min(IOS_CONCURRENCY, wanted.length) }, worker));
  } catch (err) {
    // Whatever was fetched before the failure is kept; the error is shown.
    if (Object.keys(days).length) await writeDays(db, "ios", days);
    await markSync(db, "ios", { error: err.message });
    throw err;
  }
  const written = await writeDays(db, "ios", days);
  const all = await db.collection(`${STATS}/ios/days`).select("date", "downloads", "missing").get();
  const dates = all.docs.map((d) => d.id).sort();
  await markSync(db, "ios", {
    error: null,
    days: dates.length,
    firstDay: dates[0] || null,
    lastDay: dates[dates.length - 1] || null,
    missingDays: all.docs.filter((d) => d.get("missing") === true).length,
  });
  logger.info("app store stats synced", { requested: wanted.length, days: written });
  return { platform: "ios", requested: wanted.length, days: written, lastDay: yesterday };
}

// ---------------------------------------------------------------------------
// What the console reads.
// ---------------------------------------------------------------------------

async function status(db, fetchImpl = fetch) {
  const { config, keyPresent } = await loadConfig(db);
  const [androidDoc, iosDoc, serviceAccount] = await Promise.all([db.doc(`${STATS}/android`).get(), db.doc(`${STATS}/ios`).get(), serviceAccountEmail(fetchImpl)]);
  const summary = (doc) => {
    const d = doc.exists ? doc.data() : {};
    const at = d.lastSyncAt && typeof d.lastSyncAt.toMillis === "function" ? d.lastSyncAt.toMillis() : null;
    return { ...d, lastSyncAt: at };
  };
  return {
    config,
    serviceAccount,
    android: { configured: androidConfigured(config), ...summary(androidDoc) },
    ios: { configured: iosConfigured(config, keyPresent), keyPresent, ...summary(iosDoc) },
  };
}

async function stats(db, fetchImpl = fetch) {
  const [state, androidDays, iosDays] = await Promise.all([
    status(db, fetchImpl),
    db.collection(`${STATS}/android/days`).orderBy("date").get(),
    db.collection(`${STATS}/ios/days`).orderBy("date").get(),
  ]);
  const days = { android: androidDays.docs.map((d) => d.data()), ios: iosDays.docs.map((d) => d.data()) };
  return { ...state, days, totals: totals(days) };
}

async function sync({ db, platform = "all", backfill = false, fetchImpl = fetch, storage }) {
  const { config, privateKey, keyPresent } = await loadConfig(db);
  const result = { android: null, ios: null, errors: {} };
  if (platform === "all" || platform === "android") {
    if (androidConfigured(config)) {
      try { result.android = await syncAndroid({ db, config, storage }); } catch (err) { result.errors.android = err.message; }
    } else result.errors.android = "not_configured";
  }
  if (platform === "all" || platform === "ios") {
    if (iosConfigured(config, keyPresent)) {
      try { result.ios = await syncIos({ db, config, privateKey, fetchImpl, backfill }); } catch (err) { result.errors.ios = err.message; }
    } else result.errors.ios = "not_configured";
  }
  // One platform asked for alone, and it failed: say so loudly.
  if (platform !== "all" && result.errors[platform]) {
    throw Object.assign(new Error(result.errors[platform]), { status: result.errors[platform] === "not_configured" ? 400 : 502, code: result.errors[platform] === "not_configured" ? "not_configured" : "store_sync" });
  }
  return result;
}

module.exports = {
  sync,
  stats,
  status,
  saveConfig,
  loadConfig,
  internals: {
    dayKey, isDayKey, daysBetween, decodeReport, parseCsv, parseTsv, parsePlayOverview, parsePlayCountries,
    classifyProductType, parseAppleSales, normalizePem, isPem, appleJwt, cleanConfig, androidConfigured, iosConfigured, totals,
    syncAndroid, syncIos, fetchAppleDay, CONFIG_DOC, PRIVATE_DOC, STATS, DEFAULT_PACKAGE, DEFAULT_APPLE_APP_ID,
  },
};
