// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:easy_plate/core/constants/app_enums.dart';
import 'package:easy_plate/features/grocery_list/data/models/grocery_item_model.dart';
import 'package:easy_plate/features/grocery_list/data/models/grocery_item_source_model.dart';
import 'package:easy_plate/features/grocery_list/data/models/grocery_list_model.dart';
import 'package:easy_plate/features/meal_planner/data/models/meal_item_model.dart';
import 'package:easy_plate/features/meal_planner/data/models/meal_model.dart';
import 'package:easy_plate/features/meal_planner/data/models/meal_plan_model.dart';
import 'package:easy_plate/features/my_recipes/data/models/recipe_ingredient_model.dart';
import 'package:easy_plate/features/my_recipes/data/models/recipe_model.dart';
import 'package:easy_plate/features/recipe_books/data/models/book_recipe_ref_model.dart';
import 'package:easy_plate/features/recipe_books/data/models/recipe_book_model.dart';
import 'package:easy_plate/features/user_profile/data/models/user_preferences_model.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(AccessRoleAdapter());
    registerAdapter(AppLanguageAdapter());
    registerAdapter(BookRecipeRefModelAdapter());
    registerAdapter(DietaryPreferenceAdapter());
    registerAdapter(GroceryItemModelAdapter());
    registerAdapter(GroceryItemSourceModelAdapter());
    registerAdapter(GroceryListModelAdapter());
    registerAdapter(MealItemModelAdapter());
    registerAdapter(MealModelAdapter());
    registerAdapter(MealPlanModelAdapter());
    registerAdapter(MeasurementUnitAdapter());
    registerAdapter(RecipeBookModelAdapter());
    registerAdapter(RecipeIngredientModelAdapter());
    registerAdapter(RecipeModelAdapter());
    registerAdapter(ShoppingDayAdapter());
    registerAdapter(UserPreferencesModelAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(AccessRoleAdapter());
    registerAdapter(AppLanguageAdapter());
    registerAdapter(BookRecipeRefModelAdapter());
    registerAdapter(DietaryPreferenceAdapter());
    registerAdapter(GroceryItemModelAdapter());
    registerAdapter(GroceryItemSourceModelAdapter());
    registerAdapter(GroceryListModelAdapter());
    registerAdapter(MealItemModelAdapter());
    registerAdapter(MealModelAdapter());
    registerAdapter(MealPlanModelAdapter());
    registerAdapter(MeasurementUnitAdapter());
    registerAdapter(RecipeBookModelAdapter());
    registerAdapter(RecipeIngredientModelAdapter());
    registerAdapter(RecipeModelAdapter());
    registerAdapter(ShoppingDayAdapter());
    registerAdapter(UserPreferencesModelAdapter());
  }
}
