// Carries the proxy's sizing knobs from Remote Config into the deploy.
//
// minInstances, maxInstances and timeoutSeconds are *deploy-time* properties of
// a Cloud Function: they describe the instance Google provisions, so nothing
// read inside a request can change them. Remote Config is still the right place
// to keep them — one console, next to the flags the app already reads — and
// this script is what carries the values across. It runs as the functions
// predeploy hook, reads the three `gemini_*` parameters from the live template,
// and writes them into the `.env.<project>` file the `defineInt` params in
// aiProxy.js resolve from.
//
// So a value changed in the console takes effect on the next deploy, not
// immediately. That is not a shortcut around a live update — there is no live
// update to be had for these three.
const fs = require("node:fs");
const path = require("node:path");

const { initializeApp, applicationDefault } = require("firebase-admin/app");
const { getRemoteConfig } = require("firebase-admin/remote-config");

// Remote Config key -> the env var aiProxy.js reads, and the value used when
// the console has no answer for us.
const KNOBS = [
  { remote: "gemini_minInstances", env: "GEMINI_MIN_INSTANCES", fallback: 1 },
  { remote: "gemini_maxInstances", env: "GEMINI_MAX_INSTANCES", fallback: 10 },
  { remote: "gemini_timeoutSeconds", env: "GEMINI_TIMEOUT_SECONDS", fallback: 120 },
];

// Google refuses a deploy outside these, and a typo in the console should fail
// here with a readable message rather than half way through a deploy.
const BOUNDS = {
  GEMINI_MIN_INSTANCES: [0, 100],
  GEMINI_MAX_INSTANCES: [1, 1000],
  GEMINI_TIMEOUT_SECONDS: [1, 3600],
};

function projectId() {
  const fromEnv =
    process.env.GCLOUD_PROJECT ||
    process.env.FIREBASE_PROJECT ||
    process.env.GOOGLE_CLOUD_PROJECT;
  if (fromEnv) return fromEnv;
  const rc = JSON.parse(
    fs.readFileSync(path.join(__dirname, "..", "..", ".firebaserc"), "utf8"),
  );
  return rc.projects.default;
}

/// The parsing, kept separate from the network so it can be reasoned about (and
/// tested) on its own. A parameter that exists but carries a blank or
/// non-numeric value is treated as unset: a stray keystroke in the console must
/// not deploy the proxy with zero warm instances or a one-second timeout.
function resolveKnob(parameter, knob) {
  const raw = parameter?.defaultValue?.value;
  if (raw === undefined || String(raw).trim() === "") return knob.fallback;

  const parsed = Number(String(raw).trim());
  if (!Number.isInteger(parsed)) {
    throw new Error(
      `Remote Config ${knob.remote}="${raw}" is not a whole number`,
    );
  }

  const [min, max] = BOUNDS[knob.env];
  if (parsed < min || parsed > max) {
    throw new Error(
      `Remote Config ${knob.remote}=${parsed} is outside the allowed ${min}-${max}`,
    );
  }
  return parsed;
}

function render(values) {
  const lines = [
    "# Generated by scripts/syncRuntimeOptions.js on every functions deploy.",
    "# Edit the gemini_* parameters in Firebase Remote Config, not this file.",
    ...Object.entries(values).map(([key, value]) => `${key}=${value}`),
  ];
  return `${lines.join("\n")}\n`;
}

async function main() {
  const project = projectId();
  const target = path.join(__dirname, "..", `.env.${project}`);

  let parameters = {};
  try {
    initializeApp({ credential: applicationDefault(), projectId: project });
    ({ parameters } = await getRemoteConfig().getTemplate());
  } catch (err) {
    // A deploy from a machine without application-default credentials, or an
    // offline one, should still ship — with whatever was last synced, or the
    // fallbacks. Failing the deploy over a config read would be worse than
    // deploying the previous sizing.
    console.warn(
      `[runtime-options] could not read Remote Config (${err.message}); ` +
        `keeping ${fs.existsSync(target) ? "the last synced values" : "the built-in defaults"}`,
    );
    if (fs.existsSync(target)) return;
    parameters = {};
  }

  const values = Object.fromEntries(
    KNOBS.map((knob) => [knob.env, resolveKnob(parameters[knob.remote], knob)]),
  );

  fs.writeFileSync(target, render(values));
  console.log(
    `[runtime-options] ${path.basename(target)} <- ` +
      Object.entries(values)
        .map(([k, v]) => `${k}=${v}`)
        .join(" "),
  );
}

// Exported for the unit test; the bounds check is the part worth pinning.
module.exports = { resolveKnob, render, KNOBS, BOUNDS };

if (require.main === module) {
  main().catch((err) => {
    console.error(`[runtime-options] ${err.message}`);
    process.exit(1);
  });
}
